/**
 * Print-only footer with up to three signature blocks + a generated-by
 * stamp. Pass any number of signature slots (1-3) — each rendered with a
 * pre-printed line, role label, and optional name.
 *
 *   <PrintFooter
 *     docNumber={po.number}
 *     signatures={[
 *       { label: "Prepared By",       name: "Purchase Officer" },
 *       { label: "Authorised By",     name: "Purchase HOD" },
 *       { label: "Vendor Acceptance", name: po.vendor },
 *     ]}
 *   />
 */
export default function PrintFooter({ docNumber, signatures = [] }) {
  const slots = signatures.slice(0, 3);
  return (
    <div className="print-only mt-8 pt-6 border-t border-gray-300">
      {slots.length > 0 && (
        <div
          className={`grid gap-8 mb-8 ${
            slots.length === 1
              ? "grid-cols-1"
              : slots.length === 2
                ? "grid-cols-2"
                : "grid-cols-3"
          }`}
        >
          {slots.map((s, i) => (
            <div key={i}>
              <div className="border-b border-black pb-8" />
              <div className="text-[8pt] uppercase tracking-[0.1em] font-bold text-gray-600 mt-1">
                {s.label}
              </div>
              {s.name ? (
                <div className="text-[9pt] mt-0.5">{s.name}</div>
              ) : (
                <div className="text-[9pt] text-gray-500 mt-0.5">
                  Signature &amp; Date
                </div>
              )}
            </div>
          ))}
        </div>
      )}
      <div className="flex items-center justify-between text-[7pt] text-gray-500 uppercase tracking-[0.1em]">
        <span>Generated by SCM · Meka Group</span>
        {docNumber && <span>Document: {docNumber}</span>}
      </div>
    </div>
  );
}
